name       : suitesparse
version    : 4.5.6
release    : 6
source     :
    - http://faculty.cse.tamu.edu/davis/SuiteSparse/SuiteSparse-4.5.6.tar.gz : de5fb496bdc029e55955e05d918a1862a177805fbbd5b957e8b5ce6632f6c77e
license    :
    - BSD-3-Clause
    - GPL-2.0
    - LGPL-2.1
component  : programming
summary    : A suite of Sparse matrix packages
description: |
    A suite of Sparse matrix packages
builddeps  :
    - intel-tbb-devel
    - metis-devel
    - openblas-devel
setup      : |
    %patch -p1 < $pkgfiles/suitesparse-link-tbb.patch
build      : |
    BLAS=-lopenblas \
    LAPACK=-lopenblas \
    MY_METIS_LIB=/usr/lib/libmetis.so \
    SPQR_CONFIG=-DHAVE_TBB \
    TBB=-ltbb %make
install    : |
    BLAS=-lopenblas \
    INSTALL_INCLUDE=$installdir/usr/include \
    INSTALL_LIB=$installdir/%libdir%  \
    LAPACK=-lopenblas \
    MY_METIS_LIB=/usr/lib/libmetis.so \
    SPQR_CONFIG=-DHAVE_TBB \
    TBB=-ltbb %make_install
    #rm -f $installdir/%libdir%/*.a
