name       : suitesparse
version    : 4.5.3
release    : 4
source     :
    - http://faculty.cse.tamu.edu/davis/SuiteSparse/SuiteSparse-4.5.3.tar.gz : 6199a3a35fbce82b155fd2349cf81d2b7cddaf0dac218c08cb172f9bc143f37a
license    : GPL-2.0
component  : programming
summary    : A suite of Sparse matrix packages
description: |
    A suite of Sparse matrix packages
builddeps  :
    - intel-tbb-devel
    - metis-devel
    - openblas-devel
setup      : |
    %patch -p1 < $pkgfiles/suitesparse-link-tbb.patch
build      : |
    BLAS=-lopenblas \
    LAPACK=-lopenblas \
    MY_METIS_LIB=/usr/lib/libmetis.so \
    SPQR_CONFIG=-DHAVE_TBB \
    TBB=-ltbb %make -C SuiteSparse_config

    BLAS=-lopenblas \
    LAPACK=-lopenblas \
    MY_METIS_LIB=/usr/lib/libmetis.so \
    SPQR_CONFIG=-DHAVE_TBB \
    TBB=-ltbb %make
    mkdir shared
    ld -shared -soname libsuitesparseconfig.so.4 -o \
        shared/libsuitesparseconfig.so.4.5.3 --whole-archive \
        SuiteSparse_config/libsuitesparseconfig.a -lm && \
    ln -sf libsuitesparseconfig.so.4.5.3 shared/libsuitesparseconfig.so
    ld -shared -soname libamd.so.2 -o shared/libamd.so.2.4.6 \
        --whole-archive AMD/Lib/libamd.a -L./shared -lsuitesparseconfig -lm && \
    ln -sf libamd.so.2.4.6 shared/libamd.so
    ld -shared -soname libcamd.so.2 -o shared/libcamd.so.2.4.6 \
        --whole-archive CAMD/Lib/libcamd.a -L./shared -lsuitesparseconfig -lm && \
    ln -sf libcamd.so.2.4.6 shared/libcamd.so
    ld -shared -soname libcolamd.so.2 -o shared/libcolamd.so.2.9.6 \
        --whole-archive COLAMD/Lib/libcolamd.a -L./shared -lsuitesparseconfig -lm && \
    ln -sf libcolamd.so.2.9.6 shared/libcolamd.so
    ld -shared -soname libccolamd.so.2 -o shared/libccolamd.so.2.9.6 \
        --whole-archive CCOLAMD/Lib/libccolamd.a -L./shared -lsuitesparseconfig -lm \
        && ln -sf libccolamd.so.2.9.6 shared/libccolamd.so
    ld -shared -soname libbtf.so.1 -o shared/libbtf.so.1.2.6 \
        --whole-archive BTF/Lib/libbtf.a && \
    ln -sf libbtf.so.1.2.1 shared/libbtf.so
    ld -shared -soname libldl.so.2 -o shared/libldl.so.2.2.6 \
        --whole-archive LDL/Lib/libldl.a && \
    ln -sf libldl.so.2.2.6 shared/libldl.so
    ld -shared -soname libcholmod.so.3 -o shared/libcholmod.so.3.0.11 \
        --whole-archive CHOLMOD/Lib/libcholmod.a -lopenblas \
        -L./shared -lamd -lcamd -lcolamd -lccolamd -lsuitesparseconfig -lm && \
    ln -sf libcholmod.so.3.0.11 shared/libcholmod.so
    ld -shared -soname libspqr.so.2 -o shared/libspqr.so.2.0.7 \
        --whole-archive SPQR/Lib/libspqr.a -lopenblas \
        -L./shared -lcholmod -lsuitesparseconfig -lm && \
    ln -sf libspqr.so.2.0.7 shared/libspqr.so
    ld -shared -soname libcxsparse.so.3 -o shared/libcxsparse.so.3.1.9 \
        --whole-archive CXSparse/Lib/libcxsparse.a && \
    ln -sf libcxsparse.so.3.1.9 shared/libcxsparse.so
    ld -shared -soname libklu.so.1 -o shared/libklu.so.1.3.8 \
        --whole-archive KLU/Lib/libklu.a -L./shared -lamd -lbtf \
      -lsuitesparseconfig -lm && ln -sf libklu.so.1.3.8 shared/libklu.so
    ld -shared -soname libumfpack.so.5 -o shared/libumfpack.so.5.7.6 \
        --whole-archive UMFPACK/Lib/libumfpack.a -lopenblas -L./shared \
        -lamd -lcholmod -lsuitesparseconfig -lm && \
    ln -sf libumfpack.so.5.7.6 shared/libumfpack.so
install    : |
    BLAS=-lopenblas \
    INSTALL_INCLUDE=$installdir/usr/include \
    INSTALL_LIB=$installdir/%libdir%  \
    LAPACK=-lopenblas \
    MY_METIS_LIB=/usr/lib/libmetis.so \
    SPQR_CONFIG=-DHAVE_TBB \
    TBB=-ltbb %make_install
    rm -f $installdir/%libdir%/*.a
    cp -d shared/*.so* $installdir/%libdir%/
    /sbin/ldconfig -n $installdir/%libdir%/
    chmod 644 $installdir/usr/include/*.{h,hpp}
