name       : suitesparse
version    : 4.4.6
release    : 1
source     :
    - http://faculty.cse.tamu.edu/davis/SuiteSparse/SuiteSparse-4.4.6.tar.gz : 7f22509d87ada8506580d537efde79cf90e28e228355c18b8bf603aad1a2d7b6
license    : GPL-2.0
summary    : A suite of Sparse matrix packages
description: |
    A suite of Sparse matrix packages
builddeps  :
    - pkgconfig(blas)
    - gfortran
    - glibc-devel
    - intel-tbb-devel
build      : |
    cd %workdir%
    export CFLAGS="${CFLAGS} -DHAVE_TBB"
    %make -C SuiteSparse_config/xerbla
    %make -C SuiteSparse_config 
    for _lib in AMD CAMD COLAMD BTF KLU LDL CCOLAMD UMFPACK CHOLMOD CXSparse SPQR; do
        %make -C ${_lib} library
    done
    mkdir shared
    ld -shared -soname libsuitesparseconfig.so.4 -o \
        shared/libsuitesparseconfig.so.4.4.4 --whole-archive \
        SuiteSparse_config/libsuitesparseconfig.a -lm && \
    ln -sf libsuitesparseconfig.so.4.4.4 shared/libsuitesparseconfig.so
    ld -shared -soname libamd.so.2 -o shared/libamd.so.2.4.1 \
        --whole-archive AMD/Lib/libamd.a -L./shared -lsuitesparseconfig -lm && \
    ln -sf libamd.so.2.4.1 shared/libamd.so
    ld -shared -soname libcamd.so.2 -o shared/libcamd.so.2.4.1 \
        --whole-archive CAMD/Lib/libcamd.a -L./shared -lsuitesparseconfig -lm && \
    ln -sf libcamd.so.2.4.1 shared/libcamd.so
    ld -shared -soname libcolamd.so.2 -o shared/libcolamd.so.2.9.1 \
        --whole-archive COLAMD/Lib/libcolamd.a -L./shared -lsuitesparseconfig -lm && \
    ln -sf libcolamd.so.2.9.1 shared/libcolamd.so
    ld -shared -soname libccolamd.so.2 -o shared/libccolamd.so.2.9.1 \
        --whole-archive CCOLAMD/Lib/libccolamd.a -L./shared -lsuitesparseconfig -lm \
        && ln -sf libccolamd.so.2.9.1 shared/libccolamd.so
    ld -shared -soname libbtf.so.1 -o shared/libbtf.so.1.2.1 \
        --whole-archive BTF/Lib/libbtf.a && \
    ln -sf libbtf.so.1.2.1 shared/libbtf.so
    ld -shared -soname libldl.so.2 -o shared/libldl.so.2.2.1 \
        --whole-archive LDL/Lib/libldl.a && \
    ln -sf libldl.so.2.2.1 shared/libldl.so
    ld -shared -soname libcholmod.so.3 -o shared/libcholmod.so.3.0.5 \
        --whole-archive CHOLMOD/Lib/libcholmod.a -lblas -llapack \
        -L./shared -lamd -lcamd -lcolamd -lccolamd -lsuitesparseconfig -lm && \
    ln -sf libcholmod.so.3.0.5 shared/libcholmod.so
    ld -shared -soname libspqr.so.2 -o shared/libspqr.so.2.0.1 \
        --whole-archive SPQR/Lib/libspqr.a -lblas -llapack \
        -L./shared -lcholmod -lsuitesparseconfig -lm && \
    ln -sf libspqr.so.2.0.1 shared/libspqr.so
    ld -shared -soname libcxsparse.so.3 -o shared/libcxsparse.so.3.1.4 \
        --whole-archive CXSparse/Lib/libcxsparse.a && \
    ln -sf libcxsparse.so.3.1.4 shared/libcxsparse.so
    ld -shared -soname libklu.so.1 -o shared/libklu.so.1.3.2 \
        --whole-archive KLU/Lib/libklu.a -L./shared -lamd -lbtf \
      -lsuitesparseconfig -lm && ln -sf libklu.so.1.3.2 shared/libklu.so
    ld -shared -soname libumfpack.so.5 -o shared/libumfpack.so.5.7.1 \
        --whole-archive UMFPACK/Lib/libumfpack.a -lblas -llapack -L./shared \
        -lamd -lcholmod -lsuitesparseconfig -lm && \
    ln -sf libumfpack.so.5.7.1 shared/libumfpack.so
install    : |
    cd %workdir%
    mkdir -p $installdir/usr/{lib64,include}
    for _lib in SuiteSparse_config AMD CAMD COLAMD BTF KLU LDL CCOLAMD UMFPACK CHOLMOD CXSparse SPQR; do
      %make_install -C ${_lib} INSTALL_LIB=$installdir/%libdir% INSTALL_INCLUDE=$installdir/usr/include
    done
    rm -f $installdir/%libdir%/*.a
    cp -d shared/*.so* $installdir/%libdir%/
    /sbin/ldconfig -n $installdir/%libdir%/
    chmod 644 $installdir/usr/include/*.{h,hpp}
