name       : suitesparse
version    : 4.5.5
release    : 5
source     :
    - http://faculty.cse.tamu.edu/davis/SuiteSparse/SuiteSparse-4.5.5.tar.gz : b9a98de0ddafe7659adffad8a58ca3911c1afa8b509355e7aa58b02feb35d9b6
license    : GPL-2.0
component  : programming
summary    : A suite of Sparse matrix packages
description: |
    A suite of Sparse matrix packages
builddeps  :
    - intel-tbb-devel
    - metis-devel
    - openblas-devel
setup      : |
    %patch -p1 < $pkgfiles/suitesparse-link-tbb.patch
build      : |
    BLAS=-lopenblas \
    LAPACK=-lopenblas \
    MY_METIS_LIB=/usr/lib/libmetis.so \
    SPQR_CONFIG=-DHAVE_TBB \
    TBB=-ltbb %make
install    : |
    BLAS=-lopenblas \
    INSTALL_INCLUDE=$installdir/usr/include \
    INSTALL_LIB=$installdir/%libdir%  \
    LAPACK=-lopenblas \
    MY_METIS_LIB=/usr/lib/libmetis.so \
    SPQR_CONFIG=-DHAVE_TBB \
    TBB=-ltbb %make_install
    #rm -f $installdir/%libdir%/*.a
