name       : suitesparse
version    : 5.10.1
release    : 10
source     :
    - https://github.com/DrTimothyAldenDavis/SuiteSparse/archive/refs/tags/v5.10.1.tar.gz : acb4d1045f48a237e70294b950153e48dce5b5f9ca8190e86c2b8c54ce00a7ee
homepage   : https://people.engr.tamu.edu/davis/suitesparse.html
license    :
    - Apache-2.0
    - BSD-3-Clause
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
    - LGPL-3.0-or-later
component  : programming
libsplit   : no
summary    : A suite of Sparse matrix packages
description: |
    SuiteSparse is a suite of sparse matrix algorithms.
builddeps  :
    - pkgconfig(openblas)
    - intel-tbb-devel
    - metis-devel
    - patchelf
environment: |
    export CFLAGS="${CFLAGS} -Wno-unused-variable -Wno-comment"
    export CXXFLAGS="${CXXFLAGS} -Wno-unused-variable -Wno-comment"
setup      : |
    %patch -p1 < $pkgfiles/suitesparse-library-only.patch
build      : |
    BLAS=-lopenblas \
    LAPACK=-lopenblas \
    MY_METIS_LIB=/usr/lib/libmetis.so \
    SPQR_CONFIG=-DHAVE_TBB \
    TBB=-ltbb \
    %make
install    : |
    BLAS=-lopenblas \
    INSTALL_INCLUDE=$installdir/usr/include \
    INSTALL_LIB=$installdir/%libdir%  \
    LAPACK=-lopenblas \
    MY_METIS_LIB=/usr/lib/libmetis.so \
    SPQR_CONFIG=-DHAVE_TBB \
    TBB=-ltbb \
    %make_install

    cp -a $installdir/$workdir/* $installdir/usr
    rm -rf $installdir/home
    rm -rf $installdir/usr/lib*/*.a
    patchelf --remove-rpath $installdir/usr/lib*/lib*
